minor

diff --git a/snippets/sh-mode/hello b/snippets/sh-mode/hello
--- a/snippets/sh-mode/hello
+++ b/snippets/sh-mode/hello
@@ -6,7 +6,7 @@
 ## Description :
 ## --
 ## Created : <`(format-time-string "%Y-%m-%d" (current-time))`>
-## Updated: Time-stamp: <2013-07-30 09:26:40>
+## Updated: Time-stamp: <2013-08-04 22:57:55>
 ##-------------------------------------------------------------------
 function log()
 {
@@ -28,6 +28,34 @@ function ensure_is_root() {
     if [[ $EUID -ne 0 ]]; then
         echo "Error: This script must be run as root." 1>&2
         exit 1
+    fi
+}
+
+function request_url_post() {
+    url=${1?}
+    data=${2?}
+    header=${3:-""}
+    if [ `uname` == "Darwin" ]; then
+        data=$(echo "$data" | sed "s/\'/\\\\\"/g")
+    else
+        data=$(echo "$data" | sed "s/'/\\\\\"/g")
+    fi;
+    command="curl $header -d \"$data\" \"$url\""
+    echo -e "\n$command"
+    eval "$command"
+    if [ $? -ne 0 ]; then
+        echo "Error: fail to run $command"; exit -1
+    fi
+}
+
+function request_url_get() {
+    url=${1?}
+    header=${2:-""}
+    command="curl $header \"$url\""
+    echo -e "\n$command"
+    eval "$command"
+    if [ $? -ne 0 ]; then
+        echo "Error: fail to run $command"; exit -1
     fi
 }
 
